### ISSUE TITLE
wearableな何か作りたいです

### ISSUE THREAD

**Issue by tobyapi** [FaBoPlatform/Hack-a-thon-zero#18]
歩きスマフォしてる時に人が迫ってきたのを察知して、振動で伝えてくれるリストバンドなりベルトなりを作りたいです。

**Comment by hogenimushi** [comment]
Fabo Blickに振動があるからokかな。後は100均で見繕えそう？

**Comment by AtsushiFujii** [comment]
リストバンドは買ってきました。100均にあれば後でベルト買ってきます～
